import type { AnimalTemplate } from './types'

export const ANIMAL_POOL: AnimalTemplate[] = [
  { species: 'Octopus', displayName: 'Garry the Octopus', blurb: 'He likes bubbles and vibes.', emoji: '🐙' },
  { species: 'Fox', displayName: 'Mimi the Fox', blurb: 'She organizes snacks by color.', emoji: '🦊' },
  { species: 'Koala', displayName: 'Ned the Koala', blurb: 'He naps between standups.', emoji: '🐨' },
  { species: 'Otter', displayName: 'Pip the Otter', blurb: 'He keeps tiny rocks for luck.', emoji: '🦦' },
  { species: 'Penguin', displayName: 'Tux the Penguin', blurb: 'Slides into every sprint review.', emoji: '🐧' },
  { species: 'Sloth', displayName: 'Lola the Sloth', blurb: 'Slow plans, flawless execution.', emoji: '🦥' },
  { species: 'Panda', displayName: 'Bam the Panda', blurb: 'Brings calm to chaotic boards.', emoji: '🐼' },
  { species: 'Duck', displayName: 'Quill the Duck', blurb: 'Debates everything politely.', emoji: '🦆' },
  { species: 'Rabbit', displayName: 'Tippy the Rabbit', blurb: 'Fastest bug hunter in town.', emoji: '🐰' },
  { species: 'Whale', displayName: 'Bluey the Whale', blurb: 'Sings when tickets close.', emoji: '🐋' },
  { species: 'Capybara', displayName: 'Cappy the Capybara', blurb: 'Stays chill in every retro.', emoji: '🦫' },
  { species: 'Parrot', displayName: 'Patch the Parrot', blurb: 'Repeats only great ideas.', emoji: '🦜' },
  { species: 'Llama', displayName: 'Nori the Llama', blurb: 'Spits out unclear requirements.', emoji: '🦙' },
  { species: 'Tiger', displayName: 'Zed the Tiger', blurb: 'Protects the done column.', emoji: '🐯' },
  { species: 'Seal', displayName: 'Bloop the Seal', blurb: 'Claps for every deploy.', emoji: '🦭' },
  { species: 'Cat', displayName: 'Mochi the Cat', blurb: 'Sits on keyboards at crunch time.', emoji: '🐱' },
  { species: 'Dog', displayName: 'Rex the Dog', blurb: 'Fetches forgotten subtasks.', emoji: '🐶' },
  { species: 'Frog', displayName: 'Sprig the Frog', blurb: 'Jumps straight to blockers.', emoji: '🐸' },
  { species: 'Hedgehog', displayName: 'Spike the Hedgehog', blurb: 'Ships features carefully.', emoji: '🦔' },
  { species: 'Bee', displayName: 'Buzz the Bee', blurb: 'Always in another tab.', emoji: '🐝' },
  { species: 'Turtle', displayName: 'Shellby the Turtle', blurb: 'Prefers stable releases.', emoji: '🐢' },
  { species: 'Dolphin', displayName: 'Echo the Dolphin', blurb: 'Makes pairing sessions fun.', emoji: '🐬' },
  { species: 'Swan', displayName: 'Pearl the Swan', blurb: 'Elegant under pressure.', emoji: '🦢' },
  { species: 'Eagle', displayName: 'Ari the Eagle', blurb: 'Spots edge cases from afar.', emoji: '🦅' },
  { species: 'Bat', displayName: 'Nyx the Bat', blurb: 'Owns the late-night fixes.', emoji: '🦇' },
  { species: 'Crab', displayName: 'Clack the Crab', blurb: 'Walks sideways around scope creep.', emoji: '🦀' },
  { species: 'Shark', displayName: 'Finn the Shark', blurb: 'Slices through flaky tests.', emoji: '🦈' },
  { species: 'Horse', displayName: 'Comet the Horse', blurb: 'Gallops to sprint goals.', emoji: '🐴' },
  { species: 'Peacock', displayName: 'Rio the Peacock', blurb: 'Shows off polished releases.', emoji: '🦚' },
  { species: 'Elephant', displayName: 'Uma the Elephant', blurb: 'Never forgets acceptance criteria.', emoji: '🐘' },
]
